### ISSUE TITLE
Options System

### ISSUE THREAD

**Issue by ctolkien** [ctolkien/SodaPop.ConfigExplorer#2]
- [x] Allow override of working only on localhost
- [x] Some method of authentication?
- [ ] Allow customisation of configuration items which are redacted.
- [x] Override endpoint URL. Currently hard-coded to use `/options`.

**Comment by ctolkien** [comment]
These will probably need to be split out into individual issues.

**Comment by poke** [comment]
Sent a PR for configuration through options.

For authentication/authorization, I would consider the middleware to go through endpoint routing in 3.0. That way, we would get that mostly for free.

For the redacted-customization, maybe the options could include some callback that gets called and can redact entries.

**Comment by ctolkien** [comment]
>For the redacted-customization, maybe the options could include some callback that gets called and can redact entries.

Either this, or perhaps you implement and register an `IConfigRedacterererer`, and we pick up all of them from DI and run a known method on them?

**Comment by poke** [comment]
Or maybe support both so you can have different redacterererererers depending on which config explorer you refer to but still allow it to be configured through DI.

E.g. ASP.NET Core authentication has this `Type EventsType` property that is used to auto-provide an events type if the `object Events` property is not set. We could do the same and retrieve it through DI if the `RedacterererererererererType` is specified.

Not sure if all this is worth the effort though. Chances are, people don’t need that much configuration.

**Comment by ctolkien** [comment]
I don't think we need an `IRedacterererere` we now get auth for endpoint routing. Closing!
